language: ruby
rvm:
    - 2.3.0
env:
    - DB=postgres
before_install:
    - gem install bundler
    - bundle install
    - RAILS_ENV=test bundle exec rake db:create db:migrate test
services:
    - redis-server
